service:
  name: service-jaeger
  namespace: aicares
image:
  repository: quay.io/jaegertracing/jaeger
  tag: "2.14.1"
containerPort: 16686
resources:
  limits:
    memory: "200Mi"
  requests:
    memory: "64Mi"
    cpu: "50m"
env: []
nodeSelector:
  eks.amazonaws.com/nodegroup: graviton-workers
